language: node_js
node_js:
- "node"
addons:
  sonarcloud:
    organization: "kbytesys-github"
    token:
      secure: $SONAR_TOKEN
cache:
  directories:
  - "node_modules"
script:
  - sonar-scanner

